#!/bin/sh

# ensure args are passed
[ -z "$1" ] && exit 1

author="$(echo "$1" | cut -d '/' -f1)"
repository="$(echo "$1" | cut -d '/' -f2)"

repo_url="https://api.github.com/repos/${author}/${repository}/releases"

latest_version="$(curl -s "$repo_url" | grep browser_ | cut -d\" -f4 | head -n 1 | sed 's/.*'"$author"'\/'"$repository"'//' | cut -d '/' -f4)"

[ "$2" == "--dmenu" ] && wget "$(curl -s "$repo_url" | grep browser_ | cut -d\" -f4 | grep $latest_version | dmenu -l 5)" && exit 0

wget "$(curl -s "$repo_url" | grep browser_ | cut -d\" -f4 | grep "$latest_version" | head -n 1)"

# vim: syntax=sh
