#!/bin/bash

#
# this script is intentionally somewhat less than comprehensive - this is not intended to be used on code that you
# are writing yourself. Rather, this is intended to simplify the process of reading downloaded webpages in this day and age
# in which nearly all webpages are obfuscated and "minified"
#

# misc vars
text_buffer=""

# if text is provided, load into buffer var
[ -f "$1" ] && text_buffer="$(cat $1)" || read text_buffer

# ensure we have any text to format 
[ -z "$text_buffer" ] && echo "no html to format. Stop." >&2 && exit 1

###
### format html
###

# put newlines after every '>' symbol
text_buffer="${text_buffer//>/>\\n}"

###
### format js
###

# put newlines after every open bracket
text_buffer="${text_buffer//{/\{\\n}}"

# put newlines after every semicolon
text_buffer="${text_buffer//\;/\;\\n}"

echo -e "$text_buffer"

# vim: syntax=sh
