#!/bin/bash

#
# utility script to change a player's number of lunar coins in Risk of Rain.
# usage:
# 		- first argument must be a path to the user's config file
# 		- second argument may be a new value to set for coins. If this value is not present,
# 		  the current value will be printed and the script will stop. Note that any non-digit
# 		  characters will be automatically stripped from this argument.
#

# ensure that we have a file to work with
([ -z "$1" ] || [ ! -f "$1" ]) && echo "please supply a valid path to the config file, usually found at \"~/.steam/steam/userdata/[numbers]/632360/remote/UserProfiles/[lots of numbers and letters with some dashes].xml\""

# set current coins equal to whatever value is between the 'coins' tags in the xml body (weird syntax is to prevent unwanted output to stdout)
read current_coins < <(cat "$1" | sed -n 's:.*<coins>\(.*\)</coins>.*:\1:p')

# if there is no new value to set, print current value
[ -z "$2" ] && echo "you have $current_coins lunar coins." && exit 0

# take only numbers for new value so as to not corrupt data
new_value="$(echo $2 | sed 's/[^0-9]/ /g;s/ //g;s/\n//g')"

(cat $1 | sed 's:\(.*<coins>\).*\(</coins>.*\):\1'"$new_value"'\2:p' | tee $1) 1>/dev/null

echo "$current_coins -> $new_value"
