#!/bin/bash

# @author Ronan Kelley
# run this script in any folder containing AUR downloads
# (personally I made the directory ~/AUR on my arch installs)
# if you use multiple directories to store AUR folders, consider wrapping
# this script in a for loop

# get information necessary to cut directory string to size
curDir=$(pwd)
curDirLen=${#curDir}
curDirLen=$curDirLen+1

# iterate through every directory in ${curDir}
for file in ${curDir}/*
do
	curFile=${file:curDirLen}
	if ! [ -z $curFile ] && ! [[ $curFile =~ "." ]] && [ -d $curFile ]
	then
		cd $curFile
		
		if [ -z "$(git pull | grep -i 'already up to date')" ]
			then
				[ -f "premake.sh" ] && ./premake.sh
				makepkg -sic
				[ -f "postmake.sh" ] && ./postmake.sh
			else
				# no need to update packages that are already fully updated
				echo "$curFile is already up to date, skipping"
		fi
		cd ..
	fi
done

# vim: syntax=sh
