#!/bin/bash

# get sudo permissions for this script
sudo -v

# update
sudo apt update
sudo apt upgrade -y

# remove snapd
sudo systemctl disable --now snapd
sudo apt remove --purge snapd

# prevent automatic reinstallation of snapd from future updates
sudo apt-mark hold snapd

# delete motd ads (really, canonical?)
sudo rm -rf /etc/update-motd.d/*motd-news

# handle args
for arg in $*; do
	case $arg in
		"+install")
			# install all programs listed under install_list
			echo "installing extra software"
			for entry in $(cat install_list); do
				install_list="$install_list $entry"
			done
			# if install list is empty, don't try to install anything
			[ ! -z "$install_list" ] && sudo apt install $install_list -y
			;;
		"+hostname")
			# get new hostname to set
			read new_hostname
			# attempt to set new hostname if not empty
			[ ! -z "$new_hostname" ] && sudo hostnamectl set-hostname $new_hostname
			;;
	esac
done
