#!/bin/bash

# get sudo permissions for this script
sudo -v

# update
sudo apt update
sudo apt upgrade

# remove snapd
sudo systemctl disable --now snapd
sudo apt remove --purge snapd

# prevent automatic reinstallation of snapd from future updates
sudo apt-mark hold snapd

# delete motd ads (really, canonical?)
sudo rm -rf /etc/update-motd.d/*motd-news
